### ISSUE TITLE
How to calculate the coremark score i.e. coremark/MHz ?

### ISSUE THREAD

**Issue by strikersps** [eembc/coremark#41]
How to calculate the coremark score from the logs which is generated as a result of coremark run. Can you emphasize more on that because I am able to run the coremark on the embedded device succesfully but not able to infer the score like which variables I need to consider to calculate the coremark/MHz score.

For E.g. what would the coremark score for the following output and how do we calculate the coremark/MHz value for reporting and inference purposes?
`CoreMark 1.0 : 6508.490622 / GCC3.4.4 -O2 / Heap`

**Comment by petertorelli** [comment]
The CoreMark score is the number of iterations per second of the loop, in your example it is 6508.49... You just divide that by the clock speed in MHz of the core that the process was running on. The core frequency is not printed in the log file because there is no portable way to determine it; you should know from your IDE/BSP clock tree settings.

**Comment by strikersps** [comment]
Thanks @petertorelli
